name: Build & Release MCP-1Panel

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag (e.g. v0.1.0)"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64, arm, s390x, ppc64le]
        include:
          - goarch: arm
            goarm: 7

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build Binary
        run: |
          mkdir -p build
          export GOARM=${{ matrix.goarm || '' }}
          CGO_ENABLED=0 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} GOARM=$GOARM \
          go build -trimpath -ldflags '-s -w' -o ./build/mcp-1panel ./main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mcp-1panel-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goarm && format('v{0}', matrix.goarm) || '' }}
          path: build/mcp-1panel

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./release-assets

      - name: List downloaded files
        run: find ./release-assets -type f

      - name: Create Release Draft
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: ${{ github.event.inputs.version }}
          draft: true
          files: ./release-assets/**/*
