name: Build and Release MCP-1Panel

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. v1.0.0)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: linux
            goarch: arm
            goarm: 7
          - goos: linux
            goarch: s390x
          - goos: linux
            goarch: ppc64le

    name: Build for ${{ matrix.goarch }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build Binary
        run: |
          mkdir -p build
          ARCH=${{ matrix.goarch }}
          if [ "${ARCH}" = "arm" ]; then
            ARCH="armv${{ matrix.goarm }}"
          fi
          OUTPUT_NAME=mcp-1panel-${ARCH}
          CGO_ENABLED=0 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} GOARM=${{ matrix.goarm || '' }} \
          go build -trimpath -ldflags '-s -w' -o build/${OUTPUT_NAME} ./main.go

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: mcp-1panel-${{ matrix.goarch }}-${{ matrix.goarm || 'default' }}
          path: build/*

  release:
    needs: build
    runs-on: ubuntu-latest
    name: Create Release
    steps:
      - name: Download all binary artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./release-assets

      - name: Move all binaries to one folder
        run: |
          mkdir -p final-release
          find ./release-assets -type f -exec mv {} final-release/ \;

      - name: List final files
        run: ls -lh final-release

      - name: Create GitHub Release Draft
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: ${{ github.event.inputs.version }}
          draft: true
          files: final-release/*
