name: Build & Release MCP-1Panel

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag (e.g. v0.1.0)"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        include:
          - goarch: amd64
          - goarch: arm64
          - goarch: arm
            goarm: 7
          - goarch: s390x
          - goarch: ppc64le

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build Binary with Target Name
        run: |
          mkdir -p build
          ARCH=${{ matrix.goarch }}
          if [ "${ARCH}" = "arm" ]; then
            ARCH="armv${{ matrix.goarm }}"
          fi
          FILENAME=mcp-1panel-${ARCH}
          CGO_ENABLED=0 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} GOARM=${{ matrix.goarm || '' }} \
          go build -trimpath -ldflags '-s -w' -o build/${FILENAME} ./main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-binaries
          path: build/*
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-binaries
          path: ./release-assets

      - name: List downloaded files
        run: ls -lh ./release-assets

      - name: Create GitHub Release Draft
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: ${{ github.event.inputs.version }}
          draft: true
          files: ./release-assets/*
